[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "B" # flake8-bugbear
    ]

ignore = ["E501"] # line length


[tool.coverage.run]
omit = [
    "tests/*" # don't generate test coverage for the tests themselves
]

[tool.mypy]
strict = true 
ignore_missing_imports = true
exclude = "^tests/"